website/auth.py
# Import dari flask
from flask import Blueprint,render_template,redirect,request,flash,url_for
from flask_login import login_user, current_user, logout_user, login_required

# Import dari file lain
from website import app, db, bcrypt
from .forms import RegistarationForm,LoginForm
from .models import User, Images, Score

# Import lain
from datetime import timedelta

auth = Blueprint('auth',__name__)


@auth.route('/login',methods = ['GET','POST'])
def login():
	form = LoginForm()
	if current_user.is_authenticated:
		return redirect(url_for("views.home"))
	if form.validate_on_submit():
		user = None
		username = form.username.data
		password = form.password.data
		email = form.username.data
		user_by_Username = User.query.filter_by(username=username).first()
		user_by_email = User.query.filter_by(email=email).first()

		if user_by_Username:
			user = user_by_Username
		elif user_by_email:
			user = user_by_email

		if user:
			if bcrypt.check_password_hash(user.password,password):
				flash('Logged in succesfully!',category='success')
				login_user(user,duration = timedelta(seconds=1))
				return redirect(url_for('views.home'))
			else:
				flash('Incorrect password, try again.',category='error')
		else:
			flash("Email does not exist.",category='error')
		
	return render_template('login_page.html',form = form)


@auth.route('/SignUp',methods = ['GET','POST'])
def SignUp():
	form = RegistarationForm()
	if current_user.is_authenticated:
		return redirect(url_for("views.home"))
	if form.validate_on_submit():
		username = form.username.data
		password = form.password.data
		email = form.email.data
		user = User.query.filter_by(username=username).first()
		if username != "null" or username != None:
			if user is None:
				user = User.query.filter_by(email=email).first()
				if user is None:	
					new_user = User(username = username,password=bcrypt.generate_password_hash(password),email=email)
					db.session.add(new_user)
					db.session.commit()

					score = Score(creator_id = new_user.id)

					db.session.add(score)
					db.session.commit()

					login_user(new_user,duration = timedelta(seconds=1))
					
					return redirect(url_for('views.home'))
				else:
					flash('email address already exist',category='error')
			else:
				flash('username already exist',category='error')
		


				
	return render_template('sign_up.html',form=form)

@auth.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('views.home'))

website/views.py
# Flask Things
from flask import Blueprint,render_template,request,redirect,url_for,flash,session,jsonify
from flask_login import login_required,current_user

# Data From Other File
from website import app, db
from website.models import Images,Draft,Score,User

# Anything else
import base64
import json
from PIL import Image
from werkzeug.utils import secure_filename
import os
import time
import secrets

views = Blueprint('views',__name__)


# Home index
@views.route("/")
@views.route("/home")
@login_required
def home():

	return render_template('home.html', draft_name = 'a', image_files ='a', image_firstnames ='a', image_relations ='a', image_lastnames = 'a', user=current_user.username)

# About index
@views.route("/about")
def about():
	return render_template('about.html')

@views.route("/upload", methods = ["GET", "POST"])
@login_required
def upload_draft():
	if request.method == "POST":
		draft_name = request.form.get('draft-name')
		first_name = request.form.getlist('fname')
		last_name = request.form.getlist('lname')
		relationship = request.form.getlist('relation')
		image_files = request.files.getlist('image')

		if(not Draft.query.filter_by(name = draft_name).all()):

			draft = Draft(name = draft_name, creator_id = current_user.id)

			db.session.add(draft)
			db.session.commit()

			image_draft = []

			for x in range(len(first_name)):
				print(first_name[x])
				if first_name[x] != '':
					image_name = random_data(image_files[x])
					image_file = save_image(image_files[x],"static/Pciture_1", image_name)
					
					image = Images(first_name = first_name[x], last_name = last_name[x], relationship = relationship[x].lower(), image_file = image_name, draft_id = draft.id, creator_id = current_user.id)

					db.session.add(image)
					db.session.commit()
			return redirect(url_for("views.home"))
		
		else:
			flash("Draft already exist.",category='error')


	return render_template('upload_draft.html', user = current_user.username)


# Random picture file name

def random_data(form_picture):
	random_file_name = secrets.token_hex(16)
	f_name, f_ext = os.path.splitext(form_picture.filename)
	picture_file_name = random_file_name + f_ext

	return picture_file_name

#SAVE IMAGE
def save_image(input_image, paths, name):

	output_size = (540,450)
	filename = secure_filename(input_image.filename) 
	path = os.path.join(app.root_path, paths, name)
	image = Image.open(input_image)
	image.thumbnail(output_size)
	image.save(path)

	return filename

@views.route("/choose", methods = ["GET", "POST"])
def choose_draft():
	if request.method == "POST":
		draft_name = request.form.get('choosed')
		draft_names = Draft.query.filter_by(name = draft_name).all()
		all_name = Draft.query.all()
		print(draft_names)
		print(all_name)

		images = Images.query.filter_by(draft_id = draft_names[0].id ).all()
		# user = Images.query.filter_by(creator_id = current_user).all()
		# draft_name = Draft.query.filter_by(creator_id = current_user.id).all()
		
		image_filename = []
		image_firstname = []
		image_lastname = []
		image_relations = []
		for image in images:
			image_filename.append(image.image_file)
			image_firstname.append(image.first_name)
			image_lastname.append(image.last_name)
			image_relations.append(image.relationship)
		return render_template('home.html',draft_name = draft_name, image_files = image_filename, image_firstnames = image_firstname, image_relations = image_relations, image_lastnames = image_lastname, user=current_user.username)
			


	draft_names = []
	draft_name = Draft.query.filter_by(creator_id = current_user.id).all()
	if len(draft_name) > 0:
		for names in draft_name:
			draft_names.append(names.name)

	return render_template('choose_draft.html', draft_names = draft_names)
	
@views.route("/graph")
def graph():
	score =  Score.query.filter_by(creator_id = current_user.id).all()
	new_score = score[1:]
	total_score = score[0]
	data_keluarga_jauh = []
	data_keluarga_dekat = []
	data_teman_dekat = []
	data_teman_jauh = []

	total_data = []

	total_data.append(total_score.Keluarga_Inti_Persentage)
	total_data.append(total_score.Keluarga_Jauh_Persentage)
	total_data.append(total_score.Teman_Dekat_Persentage)
	total_data.append(total_score.Teman_Jauh_Persentage)

	for every_score in new_score:
		data_keluarga_jauh.append(every_score.Keluarga_Inti_Persentage)
		data_keluarga_dekat.append(every_score.Keluarga_Jauh_Persentage)
		data_teman_dekat.append(every_score.Teman_Dekat_Persentage)
		data_teman_jauh.append(every_score.Teman_Jauh_Persentage)


	

	return render_template('user_graph.html', data_keluarga_jauh = data_keluarga_jauh, data_keluarga_dekat = data_keluarga_dekat, data_teman_jauh = data_teman_jauh, data_teman_dekat = data_teman_dekat, total_score = total_data)




@views.route('/upload_score',methods=['POST','GET'])
def upload_score():

	score = request.form.get('score')
	keluarga_dekat = float(request.form.get('keluarga_dekat'))
	keluarga_jauh = float(request.form.get('keluarga_jauh'))
	teman_dekat = float(request.form.get('teman_dekat'))
	teman_kerja = float(request.form.get('teman_kerja'))

	
	score = Score.query.filter_by(creator_id = current_user.id).first()
	score.Keluarga_Inti_Persentage += keluarga_dekat
	score.Keluarga_Jauh_Persentage += keluarga_jauh
	score.Teman_Dekat_Persentage += teman_dekat
	score.Teman_Jauh_Persentage += teman_kerja

	# db.session.add(score)
	db.session.commit()

	print(score.Keluarga_Inti_Persentage)

	new_score = Score(Keluarga_Inti_Persentage = keluarga_dekat, Keluarga_Jauh_Persentage = keluarga_jauh, Teman_Dekat_Persentage = teman_dekat, Teman_Jauh_Persentage = teman_kerja, creator_id = current_user.id)
	db.session.add(new_score)
	db.session.commit()

	

	return render_template('user_graph.html', newest_score = new_score, total_score = score)

@views.route("/redirect_graph")
def redirect_graph():
	
	score =  Score.query.filter_by(creator_id = current_user.id).all()
	new_score = score[1:]
	total_score = score[-1]
	data_keluarga_jauh = []
	data_keluarga_dekat = []
	data_teman_dekat = []
	data_teman_jauh = []

	total_data = []

	total_data.append(total_score.Keluarga_Inti_Persentage)
	total_data.append(total_score.Keluarga_Jauh_Persentage)
	total_data.append(total_score.Teman_Dekat_Persentage)
	total_data.append(total_score.Teman_Jauh_Persentage)

	for every_score in new_score:
		data_keluarga_jauh.append(every_score.Keluarga_Inti_Persentage)
		data_keluarga_dekat.append(every_score.Keluarga_Jauh_Persentage)
		data_teman_dekat.append(every_score.Teman_Dekat_Persentage)
		data_teman_jauh.append(every_score.Teman_Jauh_Persentage)

	print(data_teman_jauh)




	

	return render_template('user_graph.html', data_keluarga_jauh = data_keluarga_jauh, data_keluarga_dekat = data_keluarga_dekat, data_teman_jauh = data_teman_jauh, data_teman_dekat = data_teman_dekat, total_score = total_data)




	

website/templates/home.html
{% extends "layout.html" %}


{% block content %}




<section class="background">
	
	<section class="Game">
		
		<img src="{{url_for('static', filename='Pciture_1/gambar1.jfif')}}"  class="q-picture" id="q-picture">

		<div class="input-container" id="input-container">
			<div class="nama">Tebak Namanya</div>
		
			<div class="input-group mb-3 answer-input">
				 <select class="form-control" id="User-Answer" placeholder="Ayo Tebak Namanya" onselect= "NextLevel(this)" >
				 	<option id='0'></option>
				 	<option id='1'></option>
				 	<option id='2'></option>
				 	<option id='3'></option>
				 	<option id='4'></option>
				 </select>
				<button class="btn btn-outline-secondary answer-btn" type="button" id="button-addon2" onclick= "NextLevel(this)">Kumpul</button>
			</div>
		</div>

	</section>


	<section class="Chosing-Game">

		<h1 class="sub-choose">
			Game Choose
		</h1>

		<ul class="Game-Choose-btn-list">	 
			 <li class="Game-Choose-btn" id="data">
			 	
			 	<a href="{{ url_for('views.choose_draft')}}"> 
			 	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-clockwise in-icon" viewBox="0 0 16 16">
				  <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
				  <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
				</svg>



			 	 <small class="href-text">Mulai Game Baru</small> </a>
			 </li>
			
			  <li class="Game-Choose-btn">
			 	<a href="{{ url_for('views.upload_draft')}}" class="">

			 	<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-folder-plus in-icon" viewBox="0 0 16 16">
				<path d="m.5 3 .04.87a1.99 1.99 0 0 0-.342 1.311l.637 7A2 2 0 0 0 2.826 14H9v-1H2.826a1 1 0 0 1-.995-.91l-.637-7A1 1 0 0 1 2.19 4h11.62a1 1 0 0 1 .996 1.09L14.54 8h1.005l.256-2.819A2 2 0 0 0 13.81 3H9.828a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 6.172 1H2.5a2 2 0 0 0-2 2zm5.672-1a1 1 0 0 1 .707.293L7.586 3H2.19c-.24 0-.47.042-.683.12L1.5 2.98a1 1 0 0 1 1-.98h3.672z"/>
				  <path d="M13.5 10a.5.5 0 0 1 .5.5V12h1.5a.5.5 0 1 1 0 1H14v1.5a.5.5 0 1 1-1 0V13h-1.5a.5.5 0 0 1 0-1H13v-1.5a.5.5 0 0 1 .5-.5z"/>
			    </svg>	
			 	<small class="href-text">Masukan Draft</small> </a>
			 </li>
			
			 
			 <li class="Game-Choose-btn life-section">
			 	 <small >Level</small> <small id="level-tag"> 1 </small> <small id="Max-level">/ </small>
			 </li>
		</ul>

	</section>

</section>





<script type="text/javascript">

	var Name = []
	var First_name = []
	var Last_name = []
	var relation = []

	

	
	var image_files = {{image_files|safe}} ;
	var image_firstnames = {{image_firstnames|safe}};
	var image_lastnames = {{image_lastnames|safe}};
	var image_relations = {{image_relations|safe}}




	for (var i = 0; i < image_files.length; i++){
		Name.push("static/Pciture_1/" + image_files[i]);
		First_name.push(image_firstnames[i].toLowerCase());
		Last_name.push(image_lastnames[i].toLowerCase());
		relation.push(image_relations[i]);
	};

	
	console.log(Name)
	console.log(First_name)



	if ( Name == '[]' ){
		Name=['static/Pciture_1/gambar1.jfif','static/Pciture_1/gambar2.jfif','static/Pciture_1/gambar3.jfif','static/Pciture_1/gambar4.jfif','static/Pciture_1/gambar5.jfif','static/Pciture_1/gambar6.jfif','static/Pciture_1/gambar7.jfif'];
		First_name =['soekarno','soeharto','bacharuddin','abdurrahman','megawati','susilo', 'joko'];
		Last_name = ['', '', 'jusuf habibie', 'wahid', 'soekarno putri', 'bambang yudhoyono', 'widodo'];
		// var Also_known = ['soekarno', '', 'b.j habibie', 'gusdur', ' megawati', 'SBY', 'jokowi' ];
		relation = ['orang terkenal','orang terkenal','orang terkenal','orang terkenal','orang terkenal','orang terkenal','orang terkenal']
	}


	
	
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script type="text/javascript" src="{{url_for('static', filename='home_Script.js')}}">
</script>

<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='home_style.css')}}">


{% endblock content %}

website/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags Search Engine Optimization -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="Twitting is your social media and universe ..." />
    <meta name="robots" content="Twitting, Social Media, Friendship" />
    <meta name="googlebot" content="Twitting, Social Media, Friendship" />
    <meta name="googlebot" content="notranslate" />
    <meta name="rating" content="adult" />
    <meta name="rating" content="RTA-5042-1996-1400-1577-RTA" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Font import  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@200&family=Shadows+Into+Light&display=swap" rel="stylesheet">

   <!-- CSS and JS -->
   <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
   <script type="text/javascript" src="{{url_for('static', filename='script.js')}}"></script>

   
    

    <header>
    
    <ul class='side-navigation'>
      <li class="vertical-navigation-list"><a id="icon-log" href="{{ url_for('views.home')}}">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16">
          <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
        </svg> 
       <small class ="logo-name">Home</small>
      </a>
      </li>
      <li class="vertical-navigation-list"><a id="icon-log" href="" > 
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
        </svg> <small class ="logo-name">News</small></a>
      </li>
      <li class="vertical-navigation-list"><a id="icon-log" href="{{ url_for('views.about')}}" >
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
        </svg> <small class ="logo-name">About</small></a>
      </li>
    
     <li class="vertical-navigation-list bottom-icon" id="login-icon">
      <a href='{{url_for("auth.login")}}' class="in-icons">
       <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
       </svg>
            {% if user %}
            <small class ="logo-name" id="login-small"> {{ user }}</small>
          {% else %}
            <small class ="logo-name" id="login-small"> Login</small>
          {% endif %}
      </a>

     </li>
     {% if user %}
       <li class="vertical-navigation-list bottom-icon">
        <a href='{{url_for("auth.logout")}}' class="in-icons">
          <small class ="logo-name" id="login-small">Logout</small>
        </a>

     </li>
      <li class="vertical-navigation-list bottom-icon">
       <a href="{{url_for('views.graph')}}" class="in-icons">
          <small class="logo-name" id="login-small">Graph</small>
        </a>
       </li>
     {% endif %}
    
    <li class="vertical-navigation-list bottom-icon" id="nigth-icon">
      <p class="in-icons" onclick="ChangeTheme(this)">
        <img src="{{ url_for('static',filename = 'icon/brightness-high.svg')}}" id="logo" width="15" height="15"> 
        <small class ="logo-name" id="logo-name"> Ligth</small></p>
    </li>
    <li lass="vertical-navigation-list">
     <!--  <h4>Find Us</h4>
    </li>
     <li class="vertical-navigation-list under-icon">
      <a href="" class="in-icons">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
      </svg> GitHub
    </a>
    </li> -->

    </ul>
   
   
   </header>

        

   {% block content %}  {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/javascript">

    if(localStorage.ligthmode == 'Ligth'){
    var body = document.body;
    document.getElementById('logo').src = "static/icon/moon.svg";
    body.classList.toggle('ligth-theme')
    }


    if(localStorage.ligthmode == 'Ligth'){
       document.getElementById('logo-name').innerText = 'Dark';
    } 
    else{
      document.getElementById('logo-name').innerText = 'Light'
    }
   

    </script>
  </body>
</html>



 

website/templates/sign_up.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login Page</title>
	<meta name="description" content="This is a CV website" />
	<meta name="rating" content="adult" />
	<meta name="rating" content="RTA-5042-1996-1400-1577-RTA" />
	<link rel="shortcut icon" href="{{ url_for('static',filename='img/favicon.ico') }}" type="image/x-icon">
	<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='signup.css')}}">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>

	<div class="background">
	{% with messages = get_flashed_messages(with_categories=true) %}

	{% if messages %}
		{% for category,message in messages %}
			{%if category == 'error'%}
			<div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role='alert'>
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
			    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
			  </svg>
 				 <div>
				{{message}}
				</div>
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
			{%endif%}

		{% endfor %}

	{% endif %}

	{% endwith %}

	




	<div class="loginbox">
		<!-- <img src="{{ url_for('static',filename ='img/pic1.jpg')}}" class="avatar"> -->
		<h1>Sign Up Here</h1>
		<form action="{{url_for('auth.SignUp')}}"method='post'>

			{{ form.hidden_tag() }}
			<fieldset>

			<div class="form-group">
					{{ form.username.label(class="form-control-label")}}

					{{ form.username(placeholder= "Enter Username" )}}
			</div>

			<div class="form-group">
					{{ form.email.label(class="form-control-label")}}

					{{ form.email(placeholder= "Enter Email", type = 'email')}}
			</div>

			<div class="form-group">
					{{ form.password.label(class="form-control-label")}}

					{{ form.password(placeholder= "Enter Password",type='password')}}
			</div>

			<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label")}}

					{{ form.confirm_password(placeholder= "Enter Confirm Pass",type='password')}}

			</div>
			
		
			</fieldset>

			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}
			</div>
			

			<small>
				<a href="{{ url_for('auth.login')}}">Have a Account? Login Here</a><br>
				<a href="{{ url_for('views.home')}}">Home</a>
			</small>

			
			
		</form>
	</div>
	</div>
</body>
</html>